-- Domain-routed active deal sheet tables (replace legacy ch_active_records).
-- Manual BigQuery-edited columns: see MANUAL_COLUMNS in functions/src/columnMappings.js
-- Run in BigQuery after migration. Optional: DROP TABLE IF EXISTS `cynetdatabase.rr_project_data.ch_active_records`;
--
-- LEVEL_2_CSM/LEVEL_3_CSM/LEVEL_4_CSM are NOT manual — they're auto-computed on every insert from
-- ONSITE_AM_EMAIL's manager hierarchy (see applyOnsiteAmCsmHierarchyForRows in bigQueryClient.js).

CREATE TABLE IF NOT EXISTS `cynetdatabase.rr_project_data.cynet_health_deal_sheet` (
  CANDIDATE_NAME STRING,
  SPECIALTY STRING,
  SPECIALTY_ID INT64,
  INTERNAL_JOB_ID INT64,
  PLACEMENT_STATUS STRING,
  FACILITY_NAME STRING,
  START_DATE DATE,
  TENTATIVE_END_DATE DATE,
  END_DATE DATE,
  REGION STRING,
  OT_RATE FLOAT64,
  BILL_RATE FLOAT64,
  CANDIDATE_STATUS STRING,
  PLACEMENT_ID INT64,
  CONTRACT_ID STRING,
  DEAL_SHEET_STATUS STRING,
  DEAL_TYPE STRING,
  CLIENT_MSP_FEE FLOAT64,
  ASSIGNMENT_RECRUITER STRING,
  ASSIGNMENT_RECRUITER_EMAIL STRING,
  BOOKING_DATE DATE,
  JOB_TYPE STRING,
  VMS STRING,
  CLIENT_OT_RATE FLOAT64,
  PROJECT_DURATION FLOAT64,
  CLIENT_CALL_BACK_RATE FLOAT64,
  CALL_BACK_RATE FLOAT64,
  CANDIDATE_ID INT64,
  PLACEMENT_TYPE STRING,
  CLIENT_ID INT64,
  CLIENT_SALES_REP STRING,
  CLIENT_SALES_REP_ID INT64,
  CLIENT_STATE STRING,
  -- CLIENT_TYPE + TYPE_OF_CLIENT: MANUAL since Aug 2026 (see MANUAL_COLUMNS). Previously enriched
  -- from the Nexus client offering's client_setting_type; now hand-edited here and carried forward
  -- unchanged on every sync. The enrich pipeline never writes them.
  CLIENT_TYPE STRING,
  CITY_ZIPCODE STRING,
  CLIENT_HOLIDAY_RATE FLOAT64,
  HOLIDAY_RATE FLOAT64,
  ON_CALL_RATE FLOAT64,
  RATE_CHANGE STRING,
  CLIENT_ON_CALL_RATE FLOAT64,
  PAY_RATE FLOAT64,
  VMS_JOB_ID STRING,
  OFFERING STRING,
  ADDITIONAL_BONUS FLOAT64,
  PO_HOURS FLOAT64,
  OFFER_TIME_START_DATE DATE,
  PARENT_CLIENT_NAME STRING,
  INITIAL_START_DATE DATE,
  WEEKLY_PER_DIEM_NON_TAXED FLOAT64,
  NBO_HOURS FLOAT64,
  BILLABLE_ORIENTATION_HRS FLOAT64,
  BILLABLE_ORIENTATION STRING,
  SCHEDULE_HOURS_1 FLOAT64,
  SCHEDULE_HOURS_2 FLOAT64,
  GM_OT FLOAT64,
  DAYS_WORKED INT64,
  CELL_PHONE STRING,
  CANDIDATE_EMAIL STRING,
  -- API-owned: candidate_contact_info[].secondary_email, then leap_email.
  SECONDARY_EMAIL STRING,
  DEAL_SHEET_ID INT64,
  -- Nexus deal sheet's own created_date (ISO instant, e.g. 2026-06-23T17:34:16Z). API-owned: written
  -- from the deal sheet detail on every sync, never hand-edited.
  DEAL_SHEET_CREATED_DATE TIMESTAMP,
  PROFESSION STRING,
  PROFESSION_ID INT64,
  HOURLY_GP FLOAT64,
  AGENCY_SWITCH INT64,
  ONSITE_OWNER INT64,
  DIRECTOR_CLIENT_PARTNERSHIP INT64,
  IS_DELETED INT64,
  GROUP_DIRECTOR INT64,
  ASSOCIATE_JUNIOR_CSM INT64,
  ONSITE_VP_AVP INT64,
  ONSITE_CLIENT_OWNER INT64,
  ASSOCIATE_SALES_PERSON INT64,
  -- STRING since Aug 2026 (was INT64, and empty in every table). Holds the client's name as spelled
  -- in Conrep ("State of NC", "Carle Foundation Hospital - RightSourcing"), matching the run-rate
  -- column it is filled from. Manual, but carried from the matched run-rate row when blank.
  CLIENT_NAME_IN_CONREP STRING,
  EDIT_DATE TIMESTAMP,
  EDITED_BY INT64,
  OWNERSHIP_EFFECTIVE_DATE DATE,
  UPDATED_AT TIMESTAMP,
  GP_PERCENTAGE FLOAT64,
  ONSITE_AM STRING,
  ONSITE_AM_EMAIL STRING,
  -- API-owned: candidate_contact_info[] leap_phone, then work_phone, then home_phone.
  SECONDARY_CELL_PHN STRING,
  PAYMENT_TYPE STRING,
  WEEKLY_WALLET_MONEY FLOAT64,
  PROVIDER_TYPE STRING,
  MSP_ID INT64,
  NEXUS_PARENT_CLIENT_ID INT64,
  MSP_NAME STRING,
  LINE_OF_BUSINESS STRING,
  RECRUITER_ID INT64,
  RECRUITER_EMP_NO STRING,
  SUBMISSION_DATE TIMESTAMP,
  ONB_CAND_DOB DATE,
  ONB_I9_RECIEVED STRING,
  ONB_SUPP_DOC1 STRING,
  ONB_SUPP_DOC1_EXP_DT DATE,
  ONB_SUPP_DOC2 STRING,
  ONB_SUPP_DOC2_EXP_DT DATE,
  ONB_E_VERIFY STRING,
  BGC_CATEGORY1 STRING,
  BGC_AMOUNT1 FLOAT64,
  BGC_CATEGORY2 STRING,
  BGC_AMOUNT2 FLOAT64,
  BGC_CATEGORY3 STRING,
  BGC_AMOUNT3 FLOAT64,
  BGC_TOTAL_BGV_COST FLOAT64,
  BGC_AGENCY_NAME STRING,
  DIVERSITY_STATUS STRING,
  BACKOUT_OR_TERMINATION STRING,
  CLIENT_RECRUITER STRING,
  CLIENT_PAYMENT_TERMS STRING,
  INVOICE_CYCLE_TO_CLIENT STRING,
  CANDIDATE_PAYMENT_TERMS STRING,
  VP STRING,
  -- Manual column (Aug 2026): hand-edited in BigQuery, frozen on every sync. VP above holds the
  -- combined VP/Sr. VP name from the hierarchy; this one is filled by hand when a separate
  -- Sr. VP is needed. No enrich or hierarchy step ever writes it.
  SR_VP STRING,
  PO_RECEIVED STRING,
  PAYLOCITY_ID STRING,
  COMMENTS STRING,
  TERMINATION_REASON STRING,
  ENTITY STRING,
  SKU_NUMBER STRING,
  FIFTYTWO_TENURE_RTO_LASTDATE DATE,
  FIFTYTWO_TENURE_CANDIDATE_STATUS STRING,
  NEW_HIRE_DATE TIMESTAMP,
  RECRUITMENT_MENTOR STRING,
  TYPE_OF_CLIENT STRING,
  ST_DT_PUSHBACK_REASON STRING,
  EXTENSION_DATE TIMESTAMP,
  EXTENSION_START_DATE DATE,
  -- "Extension/Rehire": EXTENSION / REOFFERED / REBOOKED / REBOOKED/EXTENSION.
  -- (REHIRED retired Aug 2026 -- prior-other-client deals now read REOFFERED.)
  -- Derived + recomputed on every sync by functions/src/extensionRehire.js; never hand-edited.
  EXT_OR_REHIRE_BY_RMG STRING,
  CLIENT_START_DATE DATE,
  CLIENT_CREATED_DATE DATE,
  W2_PAY_RATE FLOAT64,
  FINAL_PAY_RATE FLOAT64,
  FINAL_BILL_RATE FLOAT64,
  FINAL_COST FLOAT64,
  NET_MARGIN FLOAT64,
  MARGIN FLOAT64,
  FIRST_WEEK_HOURS FLOAT64,
  SECOND_WEEK_HOURS FLOAT64,
  TOTAL_BONUS_TAXABLE FLOAT64,
  TOTAL_BONUS_NON_TAXABLE FLOAT64,
  W2_PAY_RATE_NEW FLOAT64,
  FINAL_PAY_RATE_NEW FLOAT64,
  FINAL_COST_NEW FLOAT64,
  CALCULATED_MARGIN FLOAT64,
  REGULAR_HOURS_1 FLOAT64,
  REGULAR_HOURS_2 FLOAT64,
  FINAL_BILL_RATE_NEW FLOAT64,
  ATL STRING,
  TEAM_LEAD STRING,
  SECONDARY_AM STRING,
  ASSOCIATE_AM STRING,
  RM STRING,
  ACCOUNT_MANAGER STRING,
  ASSOCIATE_DELIVERY_DIRECTOR STRING,
  DELIVERY_POC STRING,
  DELIVERY_POC_EMP_NO STRING,
  DELIVERY_POC_EMAIL STRING,
  ACC_DIR_OR_VERT_HEAD STRING,
  CLIENT_OWNER STRING,
  PRIMARY_SALES_PERSON STRING,
  SECONDARY_SALES_PERSON STRING,
  CREDENTIALING_SPECIALIST STRING,
  CREDENTIALING_LEAD STRING,
  RECRUITER_CLUSTER_REGION STRING,
  -- Client-side counterpart of RECRUITER_CLUSTER_REGION (was PLACEMENT_CLUSTER). Manual: no enrich
  -- step writes it.
  CLIENT_CLUSTER_REGION STRING,
  CLUSTER_TYPE STRING,
  LAST_UPDATED TIMESTAMP,
  DELIVERY_DIRECTOR STRING,
  ATL_EMP_NO STRING,
  SECONDARY_RECRUITER STRING,
  SECONDARY_RECRUITER_EMP_NO STRING,
  TEAM_LEAD_EMP_NO STRING,
  RM_EMP_NO STRING,
  SECONDARY_AM_EMP_NO STRING,
  ASSOCIATE_AM_EMP_NO STRING,
  ACCOUNT_MANAGER_EMP_NO STRING,
  VP_EMP_NO STRING,
  AVP STRING,
  AVP_EMP_NO STRING,
  ASSOCIATE_DELIVERY_DIRECTOR_EMP_NO STRING,
  DELIVERY_DIRECTOR_EMP_NO STRING,
  ID STRING,
  MOVE_RUNRATE STRING,
  IS_REJECTED STRING,
  REJECTION_REASON STRING,
  DT_RATE FLOAT64,
  CLIENT_DT_RATE FLOAT64,
  LEVEL_2_CSM STRING,
  LEVEL_3_CSM STRING,
  LEVEL_4_CSM STRING,
  -- Recruiter handover snapshot: who owned the placement before the current ASSIGNMENT_RECRUITER.
  -- Written by the enrich pipeline on a recruiter change; also the source for ownership_change_logs.
  PREVIOUS_RECRUITER_NAME STRING,
  -- Extension / ownership state flags maintained outside this sync pipeline (frontend + ownership
  -- tooling). Declared here so the table shape matches; nothing in functions/src writes them.
  OWNERSHIP_DELETED BOOL,
  IS_EXTENSION BOOL,
  IS_FUTURE_ENDED BOOL,
  EXT_PENDING_ID STRING,
  EXT_CANCELLED BOOL,
);

-- CANADA (cynet health canada) — starts as a copy of health, then diverges.
--
-- Canada keeps CALCULATED_MARGIN (bill - pay, the figure MARGIN used to hold) and GROSS_MARGIN, and
-- reserves MARGIN for the API's hourly_revenue. It has no NET_MARGIN and no W2 pay family (T4 is the
-- Canada equivalent). Full rationale + the one-time migration for the live table:
-- sql/migrate_canada_deal_sheet_schema.sql
CREATE TABLE IF NOT EXISTS `cynetdatabase.rr_project_data.cynet_health_canada_deal_sheet`
LIKE `cynetdatabase.rr_project_data.cynet_health_deal_sheet`;

ALTER TABLE `cynetdatabase.rr_project_data.cynet_health_canada_deal_sheet`
  -- US-only rate/hours/bonus families
  DROP COLUMN IF EXISTS W2_PAY_RATE,
  DROP COLUMN IF EXISTS W2_PAY_RATE_NEW,
  DROP COLUMN IF EXISTS FINAL_PAY_RATE_NEW,
  DROP COLUMN IF EXISTS FINAL_COST_NEW,
  DROP COLUMN IF EXISTS FINAL_BILL_RATE_NEW,
  DROP COLUMN IF EXISTS FIRST_WEEK_HOURS,
  DROP COLUMN IF EXISTS SECOND_WEEK_HOURS,
  DROP COLUMN IF EXISTS TOTAL_BONUS_TAXABLE,
  DROP COLUMN IF EXISTS TOTAL_BONUS_NON_TAXABLE,
  DROP COLUMN IF EXISTS REGULAR_HOURS_1,
  DROP COLUMN IF EXISTS REGULAR_HOURS_2,
  DROP COLUMN IF EXISTS SCHEDULE_HOURS_2,
  DROP COLUMN IF EXISTS BILLABLE_ORIENTATION_HRS,
  DROP COLUMN IF EXISTS BILLABLE_ORIENTATION,
  -- Canada does not use net margin (bill - cost)
  DROP COLUMN IF EXISTS NET_MARGIN,
  -- Hierarchy / cluster / client-ownership columns Canada does not track (all verified empty)
  DROP COLUMN IF EXISTS EXT_PENDING_ID,
  DROP COLUMN IF EXISTS AVP,
  DROP COLUMN IF EXISTS AVP_EMP_NO,
  DROP COLUMN IF EXISTS CLIENT_OWNER,
  DROP COLUMN IF EXISTS ONSITE_CLIENT_OWNER,
  DROP COLUMN IF EXISTS CLIENT_NAME_IN_CONREP,
  DROP COLUMN IF EXISTS CLIENT_CLUSTER_REGION,
  DROP COLUMN IF EXISTS RECRUITER_CLUSTER_REGION,
  DROP COLUMN IF EXISTS CLUSTER_TYPE,
  DROP COLUMN IF EXISTS HOURLY_GP,
  DROP COLUMN IF EXISTS FIFTYTWO_TENURE_RTO_LASTDATE,
  DROP COLUMN IF EXISTS FIFTYTWO_TENURE_CANDIDATE_STATUS,
  DROP COLUMN IF EXISTS AGENCY_SWITCH,
  DROP COLUMN IF EXISTS ONSITE_OWNER,
  DROP COLUMN IF EXISTS DIRECTOR_CLIENT_PARTNERSHIP,
  DROP COLUMN IF EXISTS ASSOCIATE_JUNIOR_CSM,
  DROP COLUMN IF EXISTS ONSITE_VP_AVP,
  DROP COLUMN IF EXISTS ASSOCIATE_SALES_PERSON;

-- Canada-only columns: T4 pay rate, the renamed margin pair, and the manual sheet columns that have
-- no API source.
ALTER TABLE `cynetdatabase.rr_project_data.cynet_health_canada_deal_sheet`
  ADD COLUMN IF NOT EXISTS T4_PAY_RATE FLOAT64,
  ADD COLUMN IF NOT EXISTS CALCULATED_MARGIN FLOAT64,
  ADD COLUMN IF NOT EXISTS GROSS_MARGIN FLOAT64,
  ADD COLUMN IF NOT EXISTS CLIENT_AVERAGING_AGREEMENT STRING,
  ADD COLUMN IF NOT EXISTS CANDIDATE_AVERAGING_AGREEMENT STRING,
  ADD COLUMN IF NOT EXISTS NO_OF_TIME_EXTENSION_RECEIVED STRING;

CREATE TABLE IF NOT EXISTS `cynetdatabase.rr_project_data.cynet_locums_deal_sheet`
LIKE `cynetdatabase.rr_project_data.cynet_health_deal_sheet`;

-- Idempotent column add for tables that already existed before RECRUITER_EMP_NO was introduced.
ALTER TABLE `cynetdatabase.rr_project_data.cynet_health_deal_sheet`
  ADD COLUMN IF NOT EXISTS RECRUITER_EMP_NO STRING;
ALTER TABLE `cynetdatabase.rr_project_data.cynet_health_canada_deal_sheet`
  ADD COLUMN IF NOT EXISTS RECRUITER_EMP_NO STRING;
ALTER TABLE `cynetdatabase.rr_project_data.cynet_locums_deal_sheet`
  ADD COLUMN IF NOT EXISTS RECRUITER_EMP_NO STRING;
ALTER TABLE `cynetdatabase.rr_project_data.cynet_locums_deal_sheet`
  ADD COLUMN IF NOT EXISTS FINAL_OT_PAY_RATE FLOAT64,
  ADD COLUMN IF NOT EXISTS FINAL_HOLIDAY_PAY_RATE FLOAT64,
  ADD COLUMN IF NOT EXISTS FINAL_CALL_BACK_PAY_RATE FLOAT64;
