-- Recruiter-reassignment audit log: whenever ASSIGNMENT_RECRUITER_EMAIL changes on an existing
-- deal sheet row, one row is logged here capturing the newly-assigned recruiter's identity and
-- their manager hierarchy chain (matched via cynetdatabase.MISC.directory_employee_hierarchy).
-- The deal sheet's own hierarchy columns (TEAM_LEAD, ATL, etc.) are left untouched — this table
-- is purely an audit trail of the reassignment event.
-- Table already exists in BigQuery; this is documentation/reproducibility only.
--
-- INORGANIC_DELIVERY_POC / _EMP_NO / _EMAIL are derived (highest-seniority person present in the
-- recruiter's live chain, same priority as the deal-sheet DELIVERY_POC; email resolved from
-- MISC.directory_employees). INORGANIC_ONSITE_AM and INORGANIC_ACCOUNTS_DIRECTOR_SR_AM_VERTICAL_HEAD
-- have no designation synonym list yet and are always NULL until one is supplied.
-- SECONDARY_AM and SECONDARY_RECRUITER are intentionally not tracked in this table.
-- INORGANIC_AVP / _EMP_NO added when AVP (Associate Vice President - Delivery) was split out of VP.

CREATE TABLE IF NOT EXISTS `cynetdatabase.rr_project_data.inorganic_hierarchy_logs` (
  ID STRING NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  PLACEMENT_ID INT64,
  PLACEMENT_STATUS STRING,
  DEAL_SHEET_ID INT64,
  CANDIDATE_NAME STRING,
  CANDIDATE_ID INT64,
  OWNERSHIP_EFFECTIVE_DATE DATE,
  RECRUITER_EMAIL_ID STRING,
  RECRUITER_NAME STRING,
  INORGANIC_RECRUITER STRING,
  INORGANIC_ACCOUNT_MANAGER STRING,
  INORGANIC_ASSOCIATE_AM STRING,
  INORGANIC_RM STRING,
  INORGANIC_TL STRING,
  INORGANIC_ATL STRING,
  INORGANIC_ASSOCIATE_GROUP_DIRECTOR STRING,
  INORGANIC_DELIVERY_DIRECTOR STRING,
  INORGANIC_AVP STRING,
  INORGANIC_VP_SR_VP STRING,
  INORGANIC_DELIVERY_POC STRING,
  INORGANIC_ONSITE_AM STRING,
  INORGANIC_ACCOUNTS_DIRECTOR_SR_AM_VERTICAL_HEAD STRING,
  INORGANIC_RECRUITER_EMP_NO STRING,
  INORGANIC_ACCOUNT_MANAGER_EMP_NO STRING,
  INORGANIC_ASSOCIATE_AM_EMP_NO STRING,
  INORGANIC_RM_EMP_NO STRING,
  INORGANIC_TL_EMP_NO STRING,
  INORGANIC_ATL_EMP_NO STRING,
  INORGANIC_ASSOCIATE_GROUP_DIRECTOR_EMP_NO STRING,
  INORGANIC_DELIVERY_DIRECTOR_EMP_NO STRING,
  INORGANIC_AVP_EMP_NO STRING,
  INORGANIC_VP_SR_VP_EMP_NO STRING,
  INORGANIC_DELIVERY_POC_EMP_NO STRING,
  INORGANIC_ONSITE_AM_EMP_NO STRING,
  INORGANIC_ACCOUNTS_DIRECTOR_SR_AM_VERTICAL_HEAD_EMP_NO STRING,
  INORGANIC_DELIVERY_POC_EMAIL STRING,
  INORGANIC_LEVEL_2_CSM STRING,
  INORGANIC_LEVEL_3_CSM STRING,
  INORGANIC_LEVEL_4_CSM STRING
);
