-- Recreate rate-change log table with OLD/NEW rate snapshots and computed differences.
-- Run in BigQuery BEFORE deploying updated Firebase functions.
-- WARNING: DROP removes all existing rows in ch_rate_change_logs.

DROP TABLE IF EXISTS `cynetdatabase.rr_project_data.ch_rate_change_logs`;

CREATE TABLE `cynetdatabase.rr_project_data.ch_rate_change_logs` (
  -- System
  ID STRING NOT NULL,
  RATE_CHANGE STRING,

  -- Identification / metadata
  SKU_NUMBER STRING,
  CONTRACT_ID STRING,
  CANDIDATE_NAME STRING,
  RATE_CHANGE_EFFECTIVE_DATE DATE,
  PLACEMENT_STATUS STRING,
  START_DATE DATE,
  END_DATE DATE,
  RECRUITER STRING,
  RECRUITER_EMAIL_ID STRING,
  ACCOUNT_MANAGER STRING,
  SECONDARY_AM STRING,
  ASSOCIATE_AM STRING,
  RM STRING,
  TEAM_LEAD STRING,
  ATL STRING,
  MSP STRING,
  END_CLIENT_DEPT_FACILITY STRING,

  -- OLD rate snapshot (from deal sheet before rate change)
  OLD_GUARANTEED_HOURS FLOAT64,
  OLD_INITIAL_PROJECT_DURATION_IN_WEEKS FLOAT64,
  OLD_ORIENTATION_HOURS FLOAT64,
  OLD_BILLABLE_ORIENTATION_HRS FLOAT64,
  OLD_BILLABLE_ORIENTATION STRING,
  OLD_ADDITIONAL_BONUS FLOAT64,
  OLD_PAY_RATE FLOAT64,
  OLD_WEEKLY_PER_DIEM FLOAT64,
  OLD_W2_PAY_RATE FLOAT64,
  OLD_FINAL_PAY_RATE FLOAT64,
  OLD_FINAL_COST FLOAT64,
  OLD_BILL_RATE FLOAT64,
  OLD_FINAL_BILL_RATE FLOAT64,
  OLD_NET_MARGIN FLOAT64,
  OLD_GROSS_MARGIN FLOAT64,
  OLD_CLIENT_MSP_FEE FLOAT64,
  OLD_GM_BASED_ON_NEW_LOADING_COST FLOAT64,

  -- NEW rate snapshot (after rate change)
  NEW_GUARANTEED_HOURS FLOAT64,
  NEW_INITIAL_PROJECT_DURATION_IN_WEEKS FLOAT64,
  NEW_ORIENTATION_HOURS FLOAT64,
  NEW_BILLABLE_ORIENTATION_HRS FLOAT64,
  NEW_BILLABLE_ORIENTATION STRING,
  NEW_ADDITIONAL_BONUS FLOAT64,
  NEW_PAY_RATE FLOAT64,
  NEW_WEEKLY_PER_DIEM FLOAT64,
  NEW_W2_PAY_RATE FLOAT64,
  NEW_FINAL_PAY_RATE FLOAT64,
  NEW_FINAL_COST FLOAT64,
  NEW_BILL_RATE FLOAT64,
  NEW_FINAL_BILL_RATE FLOAT64,
  NEW_NET_MARGIN FLOAT64,
  NEW_GROSS_MARGIN FLOAT64,
  NEW_CLIENT_MSP_FEE FLOAT64,
  NEW_GM_BASED_ON_NEW_LOADING_COST FLOAT64,

  -- Computed differences (sync: NEW - OLD)
  GM_DIFFERENCE FLOAT64,
  BR_DIFFERENCE FLOAT64,
  PROFIT_DIFFERENCE FLOAT64,

  -- Org / location
  DELIVERY_POC STRING,
  ONSITE_MANAGER STRING,
  CLIENT_STATE STRING
);
