-- Locums-only derived premium pay rates (FINAL_OT/HOLIDAY/CALL_BACK_PAY_RATE).
-- Not added to cynet_health_* or cynet_health_canada_* tables.

ALTER TABLE `cynetdatabase.rr_project_data.cynet_locums_deal_sheet`
  ADD COLUMN IF NOT EXISTS FINAL_OT_PAY_RATE FLOAT64,
  ADD COLUMN IF NOT EXISTS FINAL_HOLIDAY_PAY_RATE FLOAT64,
  ADD COLUMN IF NOT EXISTS FINAL_CALL_BACK_PAY_RATE FLOAT64;

ALTER TABLE `cynetdatabase.rr_project_data.cynet_locums_ended_deal_sheet`
  ADD COLUMN IF NOT EXISTS FINAL_OT_PAY_RATE FLOAT64,
  ADD COLUMN IF NOT EXISTS FINAL_HOLIDAY_PAY_RATE FLOAT64,
  ADD COLUMN IF NOT EXISTS FINAL_CALL_BACK_PAY_RATE FLOAT64;
