-- Recreate all_locums_runrate with a schema the sync can actually query.
--
-- The old table had 177 columns whose names diverged from every other run-rate table, so the
-- extension/manual backfill SELECTs failed with "Unrecognized name: FACILITY_NAME" (and would have
-- failed next on TENTATIVE_END_DATE, VP, DELIVERY_DIRECTOR, ...). This schema is the UNION of:
--   * all 221 columns of all_CH_data_runrate — the shape the code is written against, so every
--     column in EXTENSION_RUNRATE_HIERARCHY_COLUMNS / EXTENSION_RUNRATE_MANUAL_COLUMNS resolves
--   * the 34 locums-only columns the old table already had (marked below), so nothing is lost
-- No type conflicts existed between the two tables, so every shared column keeps its type.
--
-- Safe to drop: the table held 0 rows when this was written. VERIFY THAT AGAIN before running:
--   SELECT COUNT(*) FROM `cynetdatabase.rr_project_data.all_locums_runrate`;
--
-- The locums-only names below are kept for the loader that populates this table; the sync reads the
-- all_CH_data_runrate names. Where both exist for one concept (END_CLIENT_DEPT_FACILITY vs
-- FACILITY_NAME, TENTATIVE_DATE vs TENTATIVE_END_DATE, CLT_PYMT_TERM vs CLIENT_PAYMENT_TERMS,
-- CAND_PYMT_TERMS vs CANDIDATE_PAYMENT_TERMS, INV_CYC_TO_CLT vs INVOICE_CYCLE_TO_CLIENT,
-- VP_SRVP vs VP), populate the all_CH_data_runrate-named one or the sync will not see the value.

DROP TABLE IF EXISTS `cynetdatabase.rr_project_data.all_locums_runrate`;

CREATE TABLE `cynetdatabase.rr_project_data.all_locums_runrate` (
  CANDIDATE_NAME STRING,
  SPECIALTY STRING,
  SPECIALTY_ID INT64,
  INTERNAL_JOB_ID INT64,
  PLACEMENT_STATUS STRING,
  FACILITY_NAME STRING,
  START_DATE DATE,
  TENTATIVE_END_DATE DATE,
  END_DATE DATE,
  REGION STRING,
  OT_RATE FLOAT64,
  BILL_RATE FLOAT64,
  CANDIDATE_STATUS STRING,
  PLACEMENT_ID INT64,
  CONTRACT_ID STRING,
  DEAL_SHEET_STATUS STRING,
  DEAL_TYPE STRING,
  CLIENT_MSP_FEE FLOAT64,
  ASSIGNMENT_RECRUITER STRING,
  ASSIGNMENT_RECRUITER_EMAIL STRING,
  BOOKING_DATE DATE,
  JOB_TYPE STRING,
  VMS STRING,
  CLIENT_OT_RATE FLOAT64,
  PROJECT_DURATION FLOAT64,
  CLIENT_CALL_BACK_RATE FLOAT64,
  CALL_BACK_RATE FLOAT64,
  CANDIDATE_ID INT64,
  PLACEMENT_TYPE STRING,
  CLIENT_ID INT64,
  CLIENT_SALES_REP STRING,
  CLIENT_SALES_REP_ID INT64,
  CLIENT_STATE STRING,
  CLIENT_TYPE STRING,
  CITY_ZIPCODE STRING,
  CLIENT_HOLIDAY_RATE FLOAT64,
  HOLIDAY_RATE FLOAT64,
  ON_CALL_RATE FLOAT64,
  RATE_CHANGE STRING,
  CLIENT_ON_CALL_RATE FLOAT64,
  PAY_RATE FLOAT64,
  VMS_JOB_ID STRING,
  OFFERING STRING,
  ADDITIONAL_BONUS FLOAT64,
  PO_HOURS FLOAT64,
  OFFER_TIME_START_DATE DATE,
  PARENT_CLIENT_NAME STRING,
  INITIAL_START_DATE DATE,
  WEEKLY_PER_DIEM_NON_TAXED FLOAT64,
  NBO_HOURS FLOAT64,
  BILLABLE_ORIENTATION_HRS FLOAT64,
  BILLABLE_ORIENTATION STRING,
  SCHEDULE_HOURS_1 FLOAT64,
  SCHEDULE_HOURS_2 FLOAT64,
  GM_OT FLOAT64,
  DAYS_WORKED INT64,
  CELL_PHONE STRING,
  CANDIDATE_EMAIL STRING,
  DEAL_SHEET_ID INT64,
  PROFESSION STRING,
  PROFESSION_ID INT64,
  HOURLY_GP FLOAT64,
  AGENCY_SWITCH INT64,
  ONSITE_OWNER INT64,
  DIRECTOR_CLIENT_PARTNERSHIP INT64,
  IS_DELETED INT64,
  GROUP_DIRECTOR INT64,
  ASSOCIATE_JUNIOR_CSM INT64,
  ONSITE_VP_AVP INT64,
  ONSITE_CLIENT_OWNER INT64,
  ASSOCIATE_SALES_PERSON INT64,
  CLIENT_NAME_IN_CONREP STRING,
  EDIT_DATE TIMESTAMP,
  EDITED_BY INT64,
  OWNERSHIP_EFFECTIVE_DATE DATE,
  UPDATED_AT TIMESTAMP,
  GP_PERCENTAGE FLOAT64,
  ONSITE_AM STRING,
  ONSITE_AM_EMAIL STRING,
  SECONDARY_CELL_PHN STRING,
  PAYMENT_TYPE STRING,
  WEEKLY_WALLET_MONEY FLOAT64,
  PROVIDER_TYPE STRING,
  MSP_ID INT64,
  NEXUS_PARENT_CLIENT_ID INT64,
  MSP_NAME STRING,
  LINE_OF_BUSINESS STRING,
  RECRUITER_ID INT64,
  RECRUITER_EMP_NO STRING,
  SUBMISSION_DATE TIMESTAMP,
  ONB_CAND_DOB DATE,
  ONB_I9_RECIEVED STRING,
  ONB_SUPP_DOC1 STRING,
  ONB_SUPP_DOC1_EXP_DT DATE,
  ONB_SUPP_DOC2 STRING,
  ONB_SUPP_DOC2_EXP_DT DATE,
  ONB_E_VERIFY STRING,
  BGC_CATEGORY1 STRING,
  BGC_AMOUNT1 FLOAT64,
  BGC_CATEGORY2 STRING,
  BGC_AMOUNT2 FLOAT64,
  BGC_CATEGORY3 STRING,
  BGC_AMOUNT3 FLOAT64,
  BGC_TOTAL_BGV_COST FLOAT64,
  BGC_AGENCY_NAME STRING,
  DIVERSITY_STATUS STRING,
  BACKOUT_OR_TERMINATION STRING,
  CLIENT_RECRUITER STRING,
  CLIENT_PAYMENT_TERMS STRING,
  INVOICE_CYCLE_TO_CLIENT STRING,
  CANDIDATE_PAYMENT_TERMS STRING,
  VP STRING,
  SR_VP STRING,
  PO_RECEIVED STRING,
  PAYLOCITY_ID STRING,
  COMMENTS STRING,
  TERMINATION_REASON STRING,
  ENTITY STRING,
  SKU_NUMBER STRING,
  FIFTYTWO_TENURE_RTO_LASTDATE DATE,
  FIFTYTWO_TENURE_CANDIDATE_STATUS STRING,
  NEW_HIRE_DATE TIMESTAMP,
  RECRUITMENT_MENTOR STRING,
  TYPE_OF_CLIENT STRING,
  ST_DT_PUSHBACK_REASON STRING,
  EXTENSION_DATE TIMESTAMP,
  EXTENSION_START_DATE DATE,
  EXT_OR_REHIRE_BY_RMG STRING,
  CLIENT_START_DATE DATE,
  CLIENT_CREATED_DATE DATE,
  W2_PAY_RATE FLOAT64,
  FINAL_PAY_RATE FLOAT64,
  FINAL_BILL_RATE FLOAT64,
  FINAL_COST FLOAT64,
  NET_MARGIN FLOAT64,
  MARGIN FLOAT64,
  FIRST_WEEK_HOURS FLOAT64,
  SECOND_WEEK_HOURS FLOAT64,
  TOTAL_BONUS_TAXABLE FLOAT64,
  TOTAL_BONUS_NON_TAXABLE FLOAT64,
  W2_PAY_RATE_NEW FLOAT64,
  FINAL_PAY_RATE_NEW FLOAT64,
  FINAL_COST_NEW FLOAT64,
  CALCULATED_MARGIN FLOAT64,
  REGULAR_HOURS_1 FLOAT64,
  REGULAR_HOURS_2 FLOAT64,
  FINAL_BILL_RATE_NEW FLOAT64,
  ATL STRING,
  TEAM_LEAD STRING,
  SECONDARY_AM STRING,
  ASSOCIATE_AM STRING,
  RM STRING,
  ACCOUNT_MANAGER STRING,
  ASSOCIATE_DELIVERY_DIRECTOR STRING,
  DELIVERY_POC STRING,
  DELIVERY_POC_EMP_NO STRING,
  DELIVERY_POC_EMAIL STRING,
  ACC_DIR_OR_VERT_HEAD STRING,
  CLIENT_OWNER STRING,
  PRIMARY_SALES_PERSON STRING,
  SECONDARY_SALES_PERSON STRING,
  CREDENTIALING_SPECIALIST STRING,
  CREDENTIALING_LEAD STRING,
  RECRUITER_CLUSTER_REGION STRING,
  CLIENT_CLUSTER_REGION STRING,
  CLUSTER_TYPE STRING,
  LAST_UPDATED TIMESTAMP,
  DELIVERY_DIRECTOR STRING,
  ATL_EMP_NO STRING,
  SECONDARY_RECRUITER STRING,
  SECONDARY_RECRUITER_EMP_NO STRING,
  TEAM_LEAD_EMP_NO STRING,
  RM_EMP_NO STRING,
  SECONDARY_AM_EMP_NO STRING,
  ASSOCIATE_AM_EMP_NO STRING,
  ACCOUNT_MANAGER_EMP_NO STRING,
  VP_EMP_NO STRING,
  AVP STRING,
  AVP_EMP_NO STRING,
  ASSOCIATE_DELIVERY_DIRECTOR_EMP_NO STRING,
  DELIVERY_DIRECTOR_EMP_NO STRING,
  ID STRING,
  MOVE_RUNRATE STRING,
  IS_REJECTED STRING,
  REJECTION_REASON STRING,
  DT_RATE FLOAT64,
  CLIENT_DT_RATE FLOAT64,
  LEVEL_2_CSM STRING,
  LEVEL_3_CSM STRING,
  LEVEL_4_CSM STRING,
  PREVIOUS_RECRUITER_NAME STRING,
  OWNERSHIP_DELETED BOOL,
  IS_EXTENSION BOOL,
  IS_FUTURE_ENDED BOOL,
  EXT_PENDING_ID STRING,
  EXT_CANCELLED BOOL,
  CA_GM FLOAT64,
  CA_NM FLOAT64,
  RECRUITER_CHANGE_DATE DATE,
  BEFORE_EXTENSION_RECRUITER STRING,
  TOTAL_EXT_RECD FLOAT64,
  SECONDARY_PHN STRING,
  SECONDARY_EMAIL STRING,
  SOURCER_NAME STRING,
  EMPLOYEE_ID STRING,
  NEW_ID STRING,
  ORIGINAL_RECRUITER STRING,
  TYPE STRING,
  INORGANIC_RECRUITER STRING,
  INORGANIC_ACCOUNT_MANAGER STRING,
  INORGANIC_ASSOCIATE_AM STRING,
  INORGANIC_RM STRING,
  INORGANIC_TL STRING,
  INORGANIC_ATL STRING,
  INORGANIC_ASSOCIATE_GROUP_DIRECTOR STRING,
  INORGANIC_DELIVERY_DIRECTOR STRING,
  INORGANIC_VP_SR_VP STRING,
  INORGANIC_DELIVERY_POC STRING,
  INORGANIC_ONSITE_AM STRING,
  INORGANIC_ACCOUNTS_DIRECTOR_SR_AM_VERTICAL_HEAD STRING,
  GROSS_MARGIN FLOAT64,
  POSITION STRING,   -- locums-only
  NEXUS_INTERNAL_JOB_ID INT64,   -- locums-only
  END_CLIENT_DEPT_FACILITY STRING,   -- locums-only
  TENTATIVE_DATE DATE,   -- locums-only
  INITIAL_PROJECT_DURATION_IN_WEEKS FLOAT64,   -- locums-only
  CANDIDATE_NEXUS_ID INT64,   -- locums-only
  ACTUAL_HOURS FLOAT64,   -- locums-only
  PROJECTED_GP FLOAT64,   -- locums-only
  ACTUAL_GP FLOAT64,   -- locums-only
  ORIGINAL_START_DATE DATE,   -- locums-only
  ORIENTATION_HOURS FLOAT64,   -- locums-only
  PHONE_NUMBER STRING,   -- locums-only
  CATEGORIZATION_OF_POSITION STRING,   -- locums-only
  EFFECTIVE_DATE DATE,   -- locums-only
  CLT_PYMT_TERM STRING,   -- locums-only
  INV_CYC_TO_CLT STRING,   -- locums-only
  CAND_PYMT_TERMS STRING,   -- locums-only
  VP_SRVP STRING,   -- locums-only
  FINAL_OT_PAY_RATE FLOAT64,   -- locums-only
  FINAL_HOLIDAY_PAY_RATE FLOAT64,   -- locums-only
  FINAL_DT_PAY_RATE FLOAT64,   -- locums-only
  FINAL_CALLBACK_PAY_RATE FLOAT64,   -- locums-only
  GRP_DIR_ASSOC_GRP_DIR STRING,   -- locums-only
  CREDENTIALED_DATE DATE,   -- locums-only
  DATE_AND_TIME TIMESTAMP,   -- locums-only
  DIRECT_MANAGER STRING,   -- locums-only
  VP_SRVP_EMP_NO STRING,   -- locums-only
  GRP_DIR_ASSOC_GRP_DIR_EMP_NO STRING,   -- locums-only
  POSITION_ID INT64,   -- locums-only
  CATEGORIZATION_OF_POSITION_ID INT64,   -- locums-only
  SHIFTS STRING,   -- locums-only
  REBOOKING_EXTENSION STRING,   -- locums-only
  NO_OF_TIME_EXTENSION_RECEIVED FLOAT64,   -- locums-only
  EXTENSION_REHIRE STRING,   -- locums-only
  -- Manual loading fraction (0.15 = 15%) carried over from lo_run_rate, matching the deal sheet's
  -- cynet_locums_deal_sheet.LOADING_COST_EXCEPTION. 20 of the 913 source rows have a value.
  LOADING_COST_EXCEPTION FLOAT64   -- locums-only
);
