-- FULL REVERT — undo everything backfill_inorganic_to_organic_for_extensions.sql (and, if you ran
-- it, fix_promoted_organic_emp_no_and_delivery_poc.sql) changed, putting the deal-sheet hierarchy
-- columns back EXACTLY as they were before the backfill. Uses BigQuery time-travel: every affected
-- column is set straight back to its pre-backfill snapshot value (NOT a fill-null merge — a plain
-- revert, so promoted values like ACCOUNT_MANAGER="Neelesh Vijay" go back to their old "NA", and
-- wiped values like ASSOCIATE_AM="Sonam Chaudhary"/CY3474 and DELIVERY_DIRECTOR="Deepti Sharma"/
-- CY1166 come back). After this, it's as if the inorganic->organic promotion never ran.
--
-- Columns reverted (only the ones those scripts could have written): the 9 managed designations
-- (name + *_EMP_NO) plus DELIVERY_POC / DELIVERY_POC_EMP_NO / DELIVERY_POC_EMAIL. Matched by ID.
--
-- NOTE: BigQuery forbids reading a table via FOR SYSTEM_TIME AS OF while UPDATE-ing that same table
-- in one statement ("multiple snapshot read timestamps"). So each block first copies the snapshot
-- into a TEMP table, then UPDATEs the live table by joining that temp table.
--
-- >>> STEP 0 — SET snapshot_ts: a UTC timestamp AFTER the rows were last legitimately written but
-- >>> BEFORE you ran the buggy backfill, and within BigQuery's ~7-day time-travel window. Confirmed
-- >>> good for PLACEMENT_ID 1459449 at '2026-07-22 00:00:00 UTC' (ACCOUNT_MANAGER/VP_SRVP still
-- >>> "NA", Sonam/Deepti present). If a normal sync legitimately changed a hierarchy field between
-- >>> snapshot_ts and now, that change is reverted too — keep snapshot_ts just before the backfill.
--
-- Run: bq query --use_legacy_sql=false --project_id=cynetdatabase < this_file.sql

DECLARE snapshot_ts TIMESTAMP DEFAULT TIMESTAMP '2026-07-22 00:00:00 UTC';  -- <<< EDIT THIS

-- =========================================================================================
-- cynet_health_deal_sheet
-- =========================================================================================
CREATE TEMP TABLE snap_health AS
SELECT
  ID,
  ACCOUNT_MANAGER, ACCOUNT_MANAGER_EMP_NO, ASSOCIATE_AM, ASSOCIATE_AM_EMP_NO,
  RM, RM_EMP_NO, TEAM_LEAD, TEAM_LEAD_EMP_NO, ATL, ATL_EMP_NO,
  GRP_DIR_ASSOC_GRP_DIR, GRP_DIR_ASSOC_GRP_DIR_EMP_NO,
  DELIVERY_DIRECTOR, DELIVERY_DIRECTOR_EMP_NO, AVP, AVP_EMP_NO, VP_SRVP, VP_SRVP_EMP_NO,
  DELIVERY_POC, DELIVERY_POC_EMP_NO, DELIVERY_POC_EMAIL
FROM `cynetdatabase.rr_project_data.cynet_health_deal_sheet` FOR SYSTEM_TIME AS OF snapshot_ts;

UPDATE `cynetdatabase.rr_project_data.cynet_health_deal_sheet` d
SET
  ACCOUNT_MANAGER = s.ACCOUNT_MANAGER,
  ACCOUNT_MANAGER_EMP_NO = s.ACCOUNT_MANAGER_EMP_NO,
  ASSOCIATE_AM = s.ASSOCIATE_AM,
  ASSOCIATE_AM_EMP_NO = s.ASSOCIATE_AM_EMP_NO,
  RM = s.RM,
  RM_EMP_NO = s.RM_EMP_NO,
  TEAM_LEAD = s.TEAM_LEAD,
  TEAM_LEAD_EMP_NO = s.TEAM_LEAD_EMP_NO,
  ATL = s.ATL,
  ATL_EMP_NO = s.ATL_EMP_NO,
  GRP_DIR_ASSOC_GRP_DIR = s.GRP_DIR_ASSOC_GRP_DIR,
  GRP_DIR_ASSOC_GRP_DIR_EMP_NO = s.GRP_DIR_ASSOC_GRP_DIR_EMP_NO,
  DELIVERY_DIRECTOR = s.DELIVERY_DIRECTOR,
  DELIVERY_DIRECTOR_EMP_NO = s.DELIVERY_DIRECTOR_EMP_NO,
  AVP = s.AVP,
  AVP_EMP_NO = s.AVP_EMP_NO,
  VP_SRVP = s.VP_SRVP,
  VP_SRVP_EMP_NO = s.VP_SRVP_EMP_NO,
  DELIVERY_POC = s.DELIVERY_POC,
  DELIVERY_POC_EMP_NO = s.DELIVERY_POC_EMP_NO,
  DELIVERY_POC_EMAIL = s.DELIVERY_POC_EMAIL
FROM snap_health s
WHERE d.ID = s.ID
  AND (
    d.ACCOUNT_MANAGER IS DISTINCT FROM s.ACCOUNT_MANAGER
    OR d.ACCOUNT_MANAGER_EMP_NO IS DISTINCT FROM s.ACCOUNT_MANAGER_EMP_NO
    OR d.ASSOCIATE_AM IS DISTINCT FROM s.ASSOCIATE_AM
    OR d.ASSOCIATE_AM_EMP_NO IS DISTINCT FROM s.ASSOCIATE_AM_EMP_NO
    OR d.RM IS DISTINCT FROM s.RM
    OR d.RM_EMP_NO IS DISTINCT FROM s.RM_EMP_NO
    OR d.TEAM_LEAD IS DISTINCT FROM s.TEAM_LEAD
    OR d.TEAM_LEAD_EMP_NO IS DISTINCT FROM s.TEAM_LEAD_EMP_NO
    OR d.ATL IS DISTINCT FROM s.ATL
    OR d.ATL_EMP_NO IS DISTINCT FROM s.ATL_EMP_NO
    OR d.GRP_DIR_ASSOC_GRP_DIR IS DISTINCT FROM s.GRP_DIR_ASSOC_GRP_DIR
    OR d.GRP_DIR_ASSOC_GRP_DIR_EMP_NO IS DISTINCT FROM s.GRP_DIR_ASSOC_GRP_DIR_EMP_NO
    OR d.DELIVERY_DIRECTOR IS DISTINCT FROM s.DELIVERY_DIRECTOR
    OR d.DELIVERY_DIRECTOR_EMP_NO IS DISTINCT FROM s.DELIVERY_DIRECTOR_EMP_NO
    OR d.AVP IS DISTINCT FROM s.AVP
    OR d.AVP_EMP_NO IS DISTINCT FROM s.AVP_EMP_NO
    OR d.VP_SRVP IS DISTINCT FROM s.VP_SRVP
    OR d.VP_SRVP_EMP_NO IS DISTINCT FROM s.VP_SRVP_EMP_NO
    OR d.DELIVERY_POC IS DISTINCT FROM s.DELIVERY_POC
    OR d.DELIVERY_POC_EMP_NO IS DISTINCT FROM s.DELIVERY_POC_EMP_NO
    OR d.DELIVERY_POC_EMAIL IS DISTINCT FROM s.DELIVERY_POC_EMAIL
  );

-- =========================================================================================
-- cynet_health_canada_deal_sheet
-- =========================================================================================
CREATE TEMP TABLE snap_canada AS
SELECT
  ID,
  ACCOUNT_MANAGER, ACCOUNT_MANAGER_EMP_NO, ASSOCIATE_AM, ASSOCIATE_AM_EMP_NO,
  RM, RM_EMP_NO, TEAM_LEAD, TEAM_LEAD_EMP_NO, ATL, ATL_EMP_NO,
  GRP_DIR_ASSOC_GRP_DIR, GRP_DIR_ASSOC_GRP_DIR_EMP_NO,
  DELIVERY_DIRECTOR, DELIVERY_DIRECTOR_EMP_NO, AVP, AVP_EMP_NO, VP_SRVP, VP_SRVP_EMP_NO,
  DELIVERY_POC, DELIVERY_POC_EMP_NO, DELIVERY_POC_EMAIL
FROM `cynetdatabase.rr_project_data.cynet_health_canada_deal_sheet` FOR SYSTEM_TIME AS OF snapshot_ts;

UPDATE `cynetdatabase.rr_project_data.cynet_health_canada_deal_sheet` d
SET
  ACCOUNT_MANAGER = s.ACCOUNT_MANAGER,
  ACCOUNT_MANAGER_EMP_NO = s.ACCOUNT_MANAGER_EMP_NO,
  ASSOCIATE_AM = s.ASSOCIATE_AM,
  ASSOCIATE_AM_EMP_NO = s.ASSOCIATE_AM_EMP_NO,
  RM = s.RM,
  RM_EMP_NO = s.RM_EMP_NO,
  TEAM_LEAD = s.TEAM_LEAD,
  TEAM_LEAD_EMP_NO = s.TEAM_LEAD_EMP_NO,
  ATL = s.ATL,
  ATL_EMP_NO = s.ATL_EMP_NO,
  GRP_DIR_ASSOC_GRP_DIR = s.GRP_DIR_ASSOC_GRP_DIR,
  GRP_DIR_ASSOC_GRP_DIR_EMP_NO = s.GRP_DIR_ASSOC_GRP_DIR_EMP_NO,
  DELIVERY_DIRECTOR = s.DELIVERY_DIRECTOR,
  DELIVERY_DIRECTOR_EMP_NO = s.DELIVERY_DIRECTOR_EMP_NO,
  AVP = s.AVP,
  AVP_EMP_NO = s.AVP_EMP_NO,
  VP_SRVP = s.VP_SRVP,
  VP_SRVP_EMP_NO = s.VP_SRVP_EMP_NO,
  DELIVERY_POC = s.DELIVERY_POC,
  DELIVERY_POC_EMP_NO = s.DELIVERY_POC_EMP_NO,
  DELIVERY_POC_EMAIL = s.DELIVERY_POC_EMAIL
FROM snap_canada s
WHERE d.ID = s.ID
  AND (
    d.ACCOUNT_MANAGER IS DISTINCT FROM s.ACCOUNT_MANAGER
    OR d.ACCOUNT_MANAGER_EMP_NO IS DISTINCT FROM s.ACCOUNT_MANAGER_EMP_NO
    OR d.ASSOCIATE_AM IS DISTINCT FROM s.ASSOCIATE_AM
    OR d.ASSOCIATE_AM_EMP_NO IS DISTINCT FROM s.ASSOCIATE_AM_EMP_NO
    OR d.RM IS DISTINCT FROM s.RM
    OR d.RM_EMP_NO IS DISTINCT FROM s.RM_EMP_NO
    OR d.TEAM_LEAD IS DISTINCT FROM s.TEAM_LEAD
    OR d.TEAM_LEAD_EMP_NO IS DISTINCT FROM s.TEAM_LEAD_EMP_NO
    OR d.ATL IS DISTINCT FROM s.ATL
    OR d.ATL_EMP_NO IS DISTINCT FROM s.ATL_EMP_NO
    OR d.GRP_DIR_ASSOC_GRP_DIR IS DISTINCT FROM s.GRP_DIR_ASSOC_GRP_DIR
    OR d.GRP_DIR_ASSOC_GRP_DIR_EMP_NO IS DISTINCT FROM s.GRP_DIR_ASSOC_GRP_DIR_EMP_NO
    OR d.DELIVERY_DIRECTOR IS DISTINCT FROM s.DELIVERY_DIRECTOR
    OR d.DELIVERY_DIRECTOR_EMP_NO IS DISTINCT FROM s.DELIVERY_DIRECTOR_EMP_NO
    OR d.AVP IS DISTINCT FROM s.AVP
    OR d.AVP_EMP_NO IS DISTINCT FROM s.AVP_EMP_NO
    OR d.VP_SRVP IS DISTINCT FROM s.VP_SRVP
    OR d.VP_SRVP_EMP_NO IS DISTINCT FROM s.VP_SRVP_EMP_NO
    OR d.DELIVERY_POC IS DISTINCT FROM s.DELIVERY_POC
    OR d.DELIVERY_POC_EMP_NO IS DISTINCT FROM s.DELIVERY_POC_EMP_NO
    OR d.DELIVERY_POC_EMAIL IS DISTINCT FROM s.DELIVERY_POC_EMAIL
  );

-- =========================================================================================
-- cynet_locums_deal_sheet
-- =========================================================================================
CREATE TEMP TABLE snap_locums AS
SELECT
  ID,
  ACCOUNT_MANAGER, ACCOUNT_MANAGER_EMP_NO, ASSOCIATE_AM, ASSOCIATE_AM_EMP_NO,
  RM, RM_EMP_NO, TEAM_LEAD, TEAM_LEAD_EMP_NO, ATL, ATL_EMP_NO,
  GRP_DIR_ASSOC_GRP_DIR, GRP_DIR_ASSOC_GRP_DIR_EMP_NO,
  DELIVERY_DIRECTOR, DELIVERY_DIRECTOR_EMP_NO, AVP, AVP_EMP_NO, VP_SRVP, VP_SRVP_EMP_NO,
  DELIVERY_POC, DELIVERY_POC_EMP_NO, DELIVERY_POC_EMAIL
FROM `cynetdatabase.rr_project_data.cynet_locums_deal_sheet` FOR SYSTEM_TIME AS OF snapshot_ts;

UPDATE `cynetdatabase.rr_project_data.cynet_locums_deal_sheet` d
SET
  ACCOUNT_MANAGER = s.ACCOUNT_MANAGER,
  ACCOUNT_MANAGER_EMP_NO = s.ACCOUNT_MANAGER_EMP_NO,
  ASSOCIATE_AM = s.ASSOCIATE_AM,
  ASSOCIATE_AM_EMP_NO = s.ASSOCIATE_AM_EMP_NO,
  RM = s.RM,
  RM_EMP_NO = s.RM_EMP_NO,
  TEAM_LEAD = s.TEAM_LEAD,
  TEAM_LEAD_EMP_NO = s.TEAM_LEAD_EMP_NO,
  ATL = s.ATL,
  ATL_EMP_NO = s.ATL_EMP_NO,
  GRP_DIR_ASSOC_GRP_DIR = s.GRP_DIR_ASSOC_GRP_DIR,
  GRP_DIR_ASSOC_GRP_DIR_EMP_NO = s.GRP_DIR_ASSOC_GRP_DIR_EMP_NO,
  DELIVERY_DIRECTOR = s.DELIVERY_DIRECTOR,
  DELIVERY_DIRECTOR_EMP_NO = s.DELIVERY_DIRECTOR_EMP_NO,
  AVP = s.AVP,
  AVP_EMP_NO = s.AVP_EMP_NO,
  VP_SRVP = s.VP_SRVP,
  VP_SRVP_EMP_NO = s.VP_SRVP_EMP_NO,
  DELIVERY_POC = s.DELIVERY_POC,
  DELIVERY_POC_EMP_NO = s.DELIVERY_POC_EMP_NO,
  DELIVERY_POC_EMAIL = s.DELIVERY_POC_EMAIL
FROM snap_locums s
WHERE d.ID = s.ID
  AND (
    d.ACCOUNT_MANAGER IS DISTINCT FROM s.ACCOUNT_MANAGER
    OR d.ACCOUNT_MANAGER_EMP_NO IS DISTINCT FROM s.ACCOUNT_MANAGER_EMP_NO
    OR d.ASSOCIATE_AM IS DISTINCT FROM s.ASSOCIATE_AM
    OR d.ASSOCIATE_AM_EMP_NO IS DISTINCT FROM s.ASSOCIATE_AM_EMP_NO
    OR d.RM IS DISTINCT FROM s.RM
    OR d.RM_EMP_NO IS DISTINCT FROM s.RM_EMP_NO
    OR d.TEAM_LEAD IS DISTINCT FROM s.TEAM_LEAD
    OR d.TEAM_LEAD_EMP_NO IS DISTINCT FROM s.TEAM_LEAD_EMP_NO
    OR d.ATL IS DISTINCT FROM s.ATL
    OR d.ATL_EMP_NO IS DISTINCT FROM s.ATL_EMP_NO
    OR d.GRP_DIR_ASSOC_GRP_DIR IS DISTINCT FROM s.GRP_DIR_ASSOC_GRP_DIR
    OR d.GRP_DIR_ASSOC_GRP_DIR_EMP_NO IS DISTINCT FROM s.GRP_DIR_ASSOC_GRP_DIR_EMP_NO
    OR d.DELIVERY_DIRECTOR IS DISTINCT FROM s.DELIVERY_DIRECTOR
    OR d.DELIVERY_DIRECTOR_EMP_NO IS DISTINCT FROM s.DELIVERY_DIRECTOR_EMP_NO
    OR d.AVP IS DISTINCT FROM s.AVP
    OR d.AVP_EMP_NO IS DISTINCT FROM s.AVP_EMP_NO
    OR d.VP_SRVP IS DISTINCT FROM s.VP_SRVP
    OR d.VP_SRVP_EMP_NO IS DISTINCT FROM s.VP_SRVP_EMP_NO
    OR d.DELIVERY_POC IS DISTINCT FROM s.DELIVERY_POC
    OR d.DELIVERY_POC_EMP_NO IS DISTINCT FROM s.DELIVERY_POC_EMP_NO
    OR d.DELIVERY_POC_EMAIL IS DISTINCT FROM s.DELIVERY_POC_EMAIL
  );
